version: "3.2"
services:
  db:
    image: postgis/postgis:10-2.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ineedtoreadbooksagain
      - POSTGRES_DB=postgres
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: gunicorn app.wsgi --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
volumes:
  postgres_data:
