# Generated by Django 3.0.8 on 2020-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='fips',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
