# Generated by Django 3.0.8 on 2020-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0002_auto_20201122_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['fips']},
        ),
        migrations.AddField(
            model_name='county',
            name='fips_class',
            field=models.CharField(default='H1', max_length=2),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.CharField(default='MS', max_length=2),
        ),
        migrations.AddField(
            model_name='county',
            name='state_fips',
            field=models.IntegerField(default=28),
        ),
    ]
