# Generated by Django 3.0.8 on 2020-11-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0003_auto_20201122_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='fips',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
