# Generated by Django 3.1.3 on 2020-11-23 02:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0004_auto_20201122_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyGeoJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.county')),
            ],
        ),
    ]
