# Generated by Django 3.1.3 on 2020-11-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0008_countyprecinctgeojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPrecinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.county')),
            ],
        ),
        migrations.CreateModel(
            name='VotingPrecinctGeoJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.JSONField()),
                ('precinct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.votingprecinct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CountyPrecinctGeoJSON',
        ),
    ]
