# Generated by Django 3.1.3 on 2020-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0009_auto_20201129_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingprecinct',
            name='voting_district_code',
            field=models.CharField(max_length=20),
        ),
    ]
