# Generated by Django 3.1.3 on 2020-11-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0009_auto_20201128_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountyGeoJSON',
            new_name='CountyBorderGeoJSON',
        ),
    ]
