# Generated by Django 3.1.3 on 2020-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0010_auto_20201129_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingprecinct',
            name='name_area_description',
            field=models.CharField(max_length=280),
        ),
    ]
