# Generated by Django 3.1.3 on 2020-11-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0011_auto_20201129_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingprecinct',
            name='geojson',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VotingPrecinctGeoJSON',
        ),
    ]
