# Generated by Django 3.1.7 on 2021-02-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0012_auto_20201129_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='fips',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='FIPS Code'),
        ),
        migrations.AlterField(
            model_name='county',
            name='fips_class',
            field=models.CharField(default='H1', max_length=2, verbose_name='FIPS Class'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=50, verbose_name='County Name'),
        ),
        migrations.AlterField(
            model_name='county',
            name='state',
            field=models.CharField(default='MS', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='county',
            name='state_fips',
            field=models.CharField(default='28', max_length=2, verbose_name='State FIPS'),
        ),
        migrations.CreateModel(
            name='VotingPrecinctGeoJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.JSONField()),
                ('precinct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.votingprecinct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
