# Generated by Django 3.1.7 on 2021-02-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0013_auto_20210225_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('survey', models.CharField(max_length=140)),
                ('total', models.IntegerField()),
                ('black', models.IntegerField()),
                ('white', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('american_indian_eskimo_aleut', models.IntegerField()),
                ('asian_pacific_islander', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('age_under_5', models.IntegerField()),
                ('age_5_17', models.IntegerField()),
                ('age_18_29', models.IntegerField()),
                ('age_30_49', models.IntegerField()),
                ('age_50_64', models.IntegerField()),
                ('age_65_plus', models.IntegerField()),
            ],
        ),
    ]
