# Generated by Django 3.1.7 on 2021-02-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0014_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('survey', models.CharField(max_length=140)),
                ('total', models.IntegerField()),
                ('black', models.IntegerField()),
                ('white', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('american_indian_eskimo_aleut', models.IntegerField()),
                ('asian_pacific_islander', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('age_under_5', models.IntegerField()),
                ('age_5_17', models.IntegerField()),
                ('age_18_29', models.IntegerField()),
                ('age_30_49', models.IntegerField()),
                ('age_50_64', models.IntegerField()),
                ('age_65_plus', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.county')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Population',
        ),
    ]
