# Generated by Django 3.2.4 on 2021-06-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0015_auto_20210227_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countypopulation',
            name='age_18_29',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='age_30_49',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='age_50_64',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='age_5_17',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='age_65_plus',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='age_under_5',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='american_indian_eskimo_aleut',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='asian_pacific_islander',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='black',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='county',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='female',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='hispanic',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='male',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='total',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='white',
        ),
        migrations.RemoveField(
            model_name='countypopulation',
            name='year',
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('survey', models.CharField(max_length=140)),
                ('total', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.county')),
            ],
        ),
    ]
